#!/bin/bash -x

cd jira-e2e-tests/
docker-compose rm -sf
if [[ "$1" == "--no-test" ]]; then
    docker-compose up --force-recreate --build jira postgresql
else
    docker-compose up --force-recreate --build
fi
