/*
 * Copyright 2020 Atlassian
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.atlassian.migration.datacenter.jira.impl;

import com.atlassian.jira.config.util.JiraHome;
import com.atlassian.migration.datacenter.core.application.DatabaseConfiguration;
import com.atlassian.migration.datacenter.jira.impl.JiraConfiguration;
import com.atlassian.migration.datacenter.spi.exceptions.ConfigurationReadException;
import com.atlassian.migration.datacenter.spi.exceptions.UnsupportedPasswordEncodingException;
import com.atlassian.plugin.PluginAccessor;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

@ExtendWith(MockitoExtension.class)
class JiraConfigurationTest {
    @Mock
    JiraHome jiraHome;
    @Mock
    PluginAccessor pluginAccessor;
    @TempDir
    Path tempDir;

    @InjectMocks
    JiraConfiguration jiraConfiguration;

    @BeforeEach
    void setUp() {
        Mockito.when(jiraHome.getLocalHomePath()).thenReturn(tempDir.toString());
    }

    @Test
    void shouldRaiseFileNotFoundExceptionWhenDatabaseFileIsNotFound() {
        Exception e = assertThrows(ConfigurationReadException.class, () -> {
            jiraConfiguration.getDatabaseConfiguration();
        });
        assertEquals(FileNotFoundException.class, e.getCause().getClass());
    }

    @Test
    void shouldRaiseConfigurationExceptionWhenDatabaseFileIsNotValid() throws IOException {
        final Path file = tempDir.resolve("dbconfig.xml");
        Files.write(file, "not-xml".getBytes());

        assertThrows(ConfigurationReadException.class, () -> {
            jiraConfiguration.getDatabaseConfiguration();
        });
    }

    @Test
    void shouldRaiseAnExceptionWhenDbconfigFileIsMissingElements() throws IOException {
        String xml = "<jira-database-config><jdbc-datasource><username>jdbc_user</username><password>password</password></jdbc-datasource></jira-database-config>";
        final Path file = tempDir.resolve("dbconfig.xml");
        Files.write(file, xml.getBytes());

        assertThrows(ConfigurationReadException.class, () -> {
            jiraConfiguration.getDatabaseConfiguration();
        });
    }

    @Test
    void shouldBeValidWhenConfigurationFileIsComplete() throws Exception {
        String url = "jdbc:postgresql://dbhost:9876/dbname";
        String xml = "<jira-database-config><jdbc-datasource><url>" + url + "</url><username>jdbc_user</username><password>password</password></jdbc-datasource></jira-database-config>";
        final Path file = tempDir.resolve("dbconfig.xml");
        Files.write(file, xml.getBytes());

        DatabaseConfiguration config = jiraConfiguration.getDatabaseConfiguration();
        assertEquals("jdbc_user", config.getUsername());
        assertEquals("password", config.getPassword());
        assertEquals("dbhost", config.getHost());
        assertEquals("dbname", config.getName());
        assertEquals(9876, config.getPort());
        assertEquals(DatabaseConfiguration.DBType.POSTGRESQL, config.getType());
    }

    @Test
    void shouldBeValidWithH2() throws Exception {
        // As generated by demo setup
        String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                     "<jira-database-config>\n" +
                     "  <name>defaultDS</name>\n" +
                     "  <delegator-name>default</delegator-name>\n" +
                     "  <database-type>h2</database-type>\n" +
                     "  <schema-name>PUBLIC</schema-name>\n" +
                     "  <jdbc-datasource>\n" +
                     "    <url>jdbc:h2:file:/var/atlassian/application-data/jira/database/h2db</url>\n" +
                     "    <driver-class>org.h2.Driver</driver-class>\n" +
                     "    <username>sa</username>\n" +
                     "    <password></password>\n" +
                     "    <pool-min-size>20</pool-min-size>\n" +
                     "    <pool-max-size>20</pool-max-size>\n" +
                     "    <pool-max-wait>30000</pool-max-wait>\n" +
                     "    <min-evictable-idle-time-millis>4000</min-evictable-idle-time-millis>\n" +
                     "    <time-between-eviction-runs-millis>5000</time-between-eviction-runs-millis>\n" +
                     "    <pool-max-idle>20</pool-max-idle>\n" +
                     "    <pool-remove-abandoned>true</pool-remove-abandoned>\n" +
                     "    <pool-remove-abandoned-timeout>300</pool-remove-abandoned-timeout>\n" +
                     "  </jdbc-datasource>\n" +
                     "</jira-database-config>\n";
        final Path file = tempDir.resolve("dbconfig.xml");
        Files.write(file, xml.getBytes());

        DatabaseConfiguration config = jiraConfiguration.getDatabaseConfiguration();
        assertEquals(DatabaseConfiguration.DBType.H2, config.getType());
    }

    @Test
    void shouldBeValidWhenConfigurationDoesNotContainValueForPort() throws Exception {
        String url = "jdbc:postgresql://dbhost/dbname";
        String xml = "<jira-database-config><jdbc-datasource><url>" + url + "</url><username>jdbc_user</username><password>password</password></jdbc-datasource></jira-database-config>";
        final Path file = tempDir.resolve("dbconfig.xml");
        Files.write(file, xml.getBytes());

        DatabaseConfiguration config = jiraConfiguration.getDatabaseConfiguration();
        assertEquals("jdbc_user", config.getUsername());
        assertEquals("password", config.getPassword());
        assertEquals("dbhost", config.getHost());
        assertEquals("dbname", config.getName());
        assertEquals(5432, config.getPort());
    }

    @Test
    void shouldParseDatabaseConfigWithValidCipher() throws Exception {
        String url = "jdbc:postgresql://dbhost:9876/dbname";
        String xml = "<jira-database-config><jdbc-datasource>" +
                "<url>" + url + "</url>" +
                "<username>jdbc_user</username>" +
                "<atlassian-password-cipher-provider>com.atlassian.db.config.password.ciphers.base64.Base64Cipher</atlassian-password-cipher-provider>" +
                "<password>cGFzc3dvcmQ=</password>" +
                "</jdbc-datasource></jira-database-config>";

        final Path file = tempDir.resolve("dbconfig.xml");
        Files.write(file, xml.getBytes());

        DatabaseConfiguration databaseConfiguration = jiraConfiguration.getDatabaseConfiguration();
        assertNotNull(databaseConfiguration);

        assertEquals("jdbc_user", databaseConfiguration.getUsername());
        assertEquals("password", databaseConfiguration.getPassword());
        assertEquals("dbhost", databaseConfiguration.getHost());
        assertEquals("dbname", databaseConfiguration.getName());
    }

    @Test
    void shouldNotParseDatabaseConfigWithInvalidCipher() throws Exception {
        String url = "jdbc:postgresql://dbhost:9876/dbname";
        String xml = "<jira-database-config><jdbc-datasource>" +
                "<url>" + url + "</url>" +
                "<username>jdbc_user</username>" +
                "<atlassian-password-cipher-provider>com.atlassian.db.config.password.ciphers.algorithm.AlgorithmCipher</atlassian-password-cipher-provider>" +
                "<password>cGFzc3dvcmQ=</password>" +
                "</jdbc-datasource></jira-database-config>";

        final Path file = tempDir.resolve("dbconfig.xml");
        Files.write(file, xml.getBytes());

        assertThrows(UnsupportedPasswordEncodingException.class, () -> {
            jiraConfiguration.getDatabaseConfiguration();
        });
    }
}